"""baseline schema

The schema as it stood when Alembic was adopted, so a brand-new database
can be built with `alembic upgrade head` alone.

A database that predates Alembic already has these tables (init_db() created
them with create_all).  Mark it current instead of running this:

    uv run alembic stamp head

Revision ID: 2f58bbd81948
Revises: 
Create Date: 2026-07-31 22:23:42.812235

"""
from typing import Sequence, Union

import sqlalchemy as sa
from geoalchemy2 import Geography

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f58bbd81948'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observed_trips',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('recorded_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('trip_id', 'recorded_date')
    )
    op.create_table('reliability_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('stop_id', sa.String(), nullable=True),
    sa.Column('time_bucket', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('observed_departures', sa.Float(), nullable=True),
    sa.Column('scheduled_departures', sa.Float(), nullable=True),
    sa.Column('total_delay_seconds', sa.Float(), nullable=True),
    sa.Column('cancellation_count', sa.Float(), nullable=True),
    sa.Column('window_start_date', sa.String(), nullable=True),
    sa.Column('window_end_date', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reliability_route_stop_bucket', 'reliability_records', ['route_id', 'stop_id', 'time_bucket'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_short_name', sa.String(), nullable=True),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('service_calendar',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('service_calendar_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('exception_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_calendar_dates_date'), 'service_calendar_dates', ['date'], unique=False)
    op.create_index(op.f('ix_service_calendar_dates_service_id'), 'service_calendar_dates', ['service_id'], unique=False)
    op.create_geospatial_table('stops',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('stop_lat', sa.Float(), nullable=False),
    sa.Column('stop_lon', sa.Float(), nullable=False),
    sa.Column('stop_code', sa.String(), nullable=True),
    sa.Column('geog', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_geospatial_index('idx_stops_geog', 'stops', ['geog'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('trips',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('trip_headsign', sa.String(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('shape_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_trips_service_id'), 'trips', ['service_id'], unique=False)
    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=True),
    sa.Column('stop_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_times_stop_id'), 'stop_times', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stop_times_trip_id'), 'stop_times', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_times_trip_id'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_stop_id'), table_name='stop_times')
    op.drop_table('stop_times')
    op.drop_index(op.f('ix_trips_service_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_geospatial_index('idx_stops_geog', table_name='stops', postgresql_using='gist', column_name='geog')
    op.drop_geospatial_table('stops')
    op.drop_index(op.f('ix_service_calendar_dates_service_id'), table_name='service_calendar_dates')
    op.drop_index(op.f('ix_service_calendar_dates_date'), table_name='service_calendar_dates')
    op.drop_table('service_calendar_dates')
    op.drop_table('service_calendar')
    op.drop_table('routes')
    op.drop_index('ix_reliability_route_stop_bucket', table_name='reliability_records')
    op.drop_table('reliability_records')
    op.drop_table('observed_trips')
    # ### end Alembic commands ###
