"""shapes and shape stop positions

Track geometry for /routes legs.

Unlike the stop_routes revision this cannot back-fill: shapes come from the
feed's shapes.txt, which was never ingested, so there is nothing in the
database to derive them from.  An existing deployment gets empty tables here
and picks up geometry on its next GTFS refresh.  Until then legs simply carry
no polyline, which clients already treat as "draw a straight line".


Revision ID: a1e533f1f09b
Revises: d320750afcfc
Create Date: 2026-08-01 00:48:45.176038

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1e533f1f09b'
down_revision: Union[str, Sequence[str], None] = 'd320750afcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shapes',
    sa.Column('shape_id', sa.String(), nullable=False),
    sa.Column('points', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shape_id')
    )
    op.create_table('shape_stop_positions',
    sa.Column('shape_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shape_id'], ['shapes.shape_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('shape_id', 'stop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shape_stop_positions')
    op.drop_table('shapes')
    # ### end Alembic commands ###
