"""stop_routes lookup table

Materialises the stop -> routes mapping /stops used to derive per request
from a DISTINCT over the stop_times/trips join.

Back-filled here rather than left to the next ingest: without it an existing
deployment would answer /stops with empty routes_served until its daily GTFS
refresh happened to run.

Revision ID: d320750afcfc
Revises: 2f58bbd81948
Create Date: 2026-08-01 00:07:37.305478

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd320750afcfc'
down_revision: Union[str, Sequence[str], None] = '2f58bbd81948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop_routes',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('stop_id', 'route_id')
    )
    # ### end Alembic commands ###

    # Back-fill from the data already present.  The DISTINCT is the expensive
    # query this table exists to avoid — run once here instead of per request.
    op.execute("""
        INSERT INTO stop_routes (stop_id, route_id)
        SELECT DISTINCT st.stop_id, t.route_id
        FROM stop_times st
        JOIN trips t ON t.trip_id = st.trip_id
        WHERE st.stop_id IS NOT NULL AND t.route_id IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_routes')
    # ### end Alembic commands ###
